
-- Create table to store generated question sets
CREATE TABLE public.question_sets (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE,
  course_id UUID NOT NULL REFERENCES public.courses(id) ON DELETE CASCADE,
  selected_course_title TEXT, -- Denormalized for easier display in history
  selected_topics_json JSONB, -- Stores an array of selected topic structures, e.g., [{ "topic_index": 0, "title": "Introduction", "selected_subtopics": [{"subtopic_index": 0, "title": "Overview"}] }]
  selected_module_ids UUID[], -- Array of micro_module.id that were selected
  generation_preferences JSONB NOT NULL, -- Stores { num_questions: 10, types: ["mcq", "true_false"], difficulty: "medium" }
  generated_questions JSONB NOT NULL, -- Array of generated questions: [{ question: "...", options: ["..."], correctAnswerIndex: 0, explanation: "..." }]
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- Add comment to describe the table
COMMENT ON TABLE public.question_sets IS 'Stores sets of questions generated by users in the Question Library, along with their context and preferences.';
COMMENT ON COLUMN public.question_sets.user_id IS 'The user who generated this question set.';
COMMENT ON COLUMN public.question_sets.course_id IS 'The course context for which questions were generated.';
COMMENT ON COLUMN public.question_sets.selected_course_title IS 'Title of the course selected, denormalized for quicker history display.';
COMMENT ON COLUMN public.question_sets.selected_topics_json IS 'JSONB array detailing selected topics and their subtopics.';
COMMENT ON COLUMN public.question_sets.selected_module_ids IS 'Array of micro_module IDs selected for question generation.';
COMMENT ON COLUMN public.question_sets.generation_preferences IS 'User preferences for question generation (e.g., number, types, difficulty).';
COMMENT ON COLUMN public.question_sets.generated_questions IS 'The array of questions generated by the AI.';

-- Enable Row Level Security (RLS)
ALTER TABLE public.question_sets ENABLE ROW LEVEL SECURITY;

-- Policies for question_sets
CREATE POLICY "Users can view their own question sets"
  ON public.question_sets
  FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own question sets"
  ON public.question_sets
  FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete their own question sets"
  ON public.question_sets
  FOR DELETE
  USING (auth.uid() = user_id);

-- Create a trigger to update 'updated_at' timestamp
CREATE OR REPLACE FUNCTION public.update_question_sets_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER handle_question_sets_updated_at
  BEFORE UPDATE ON public.question_sets
  FOR EACH ROW
  EXECUTE FUNCTION public.update_question_sets_updated_at();

